services:
  - type: web
    name: geospatial-dashboard
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:server "
    plan: free
    autoDeploy: true
